### ISSUE TITLE
The name "oak" may conflict with another established language 

### ISSUE THREAD

**Issue by brecert** [thesephist/oak#1]
[oak](https://github.com/adam-mcdaniel/oakc) is another programming language named oak and from what I can tell is a little more established.

Is there a specific way to you'd want this language referred to in areas where a conflict may arise? ( package managers, projects similar to rosettacode, etc.. )

**Comment by thesephist** [comment]
Indeed! Short, memorable three-letter words are not very common, sadly. Since this project owns oaklang.org, I think "oaklang" might be good in situations where there may be ambiguity. But also it feels like both Oaks are hobby projects, so hopefully it isn''t too much of an issue.
